### ISSUE TITLE
Admission Controller via k9s issue

### ISSUE THREAD

**Issue by f1ames** [kubeshop/monokle-admission-controller#18]
When running admission controller, there is some access issue when accessing via k9s.

1. Deploy admission controller.
2. Run the binary k9s:

```
~  ▶ k9s
Error: [list watch] access denied on resource "monokle-admission-controller":"v1/pods"
Usage:
```

https://k9scli.io/topics/install/

**Comment by f1ames** [comment]
This is interesting, it only happens for a brief moment when admission controller server gets initialized. And I got similar error with kubectl (also just for a moment). I assume it might be related to cert initialization (which is not there for a brief moment), but not sure why it would affect external clients.

![monokle 20231106-5](https://github.com/kubeshop/monokle-admission-controller/assets/1061942/6383ae17-4dee-46d0-a838-de265b59aadf)

Is it the same for you @WitoDelnat?

**Comment by WitoDelnat** [comment]
I checked and this works now. When I reported the bug, my deployment never finished because of the missing container image for my architecture. This was fixed and now my deployment succeeds and k9s works again.

Thanks for looking into this. Closing the issue!
